# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-18 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('khi', 'Karachi')], default='Karachi', max_length=120),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(choices=[('pak', 'Pakistan'), ('uk', 'United Kingdom')], default='Pakistan', max_length=120),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(choices=[('sd', 'Sindh')], default='Sindh', max_length=120),
        ),
    ]
