# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-08 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20180307_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
